### ISSUE TITLE
MVP data source and resources

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/terraform-provider-sonatypeiq#1]
This is a list of data-sources and resources considered to be required for the MVP of this provider:

### Data Sources
- [x] Application
- [x] Applications
- [x] Application Categories
- [x] Config
    - [x] Base URL
    - [x] Force Base URL
- [x] Config SAML Metadata
- [x] Organization
- [x] Organizations
- [x] Role via #8 - thanks @iverberk 

### Resources
- [x] Application
- [x] Application Category via #54 
- [x] Application Role Membership via #12 - thanks @iverberk 
- [x] Config
   - [x] Base URL
   - [x] Force Base URL
- Config Artifactory Connection - descoped ❌
- [x] Config Crowd via https://github.com/sonatype-nexus-community/terraform-provider-sonatypeiq/commit/779cef0729fe70ad6de848d902eacc3172b4e277
- Config JIRA - descoped ❌ (this is in the HARD bucket due to dynamic schema requirements)
- [x] Config Mail
- [x] Config Proxy Server
- [x] Config SAML - via #59 
- [x] #2
- [x] Organization Role Membership via #12 - thanks @iverberk 
- [x] #3
- [x] User
- [x] Users
